name: config_service_g4
version: '3.9'

services:
  db:
    container_name: postgres-app
    image: postgres:17-alpine3.22
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  web-app:
    container_name: config-service
    build: .
    ports:
      - "8081:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?options=-csearch_path=config_service
      DEBUG: ${DEBUG}
      ENV: ${ENV}
    image: config-service
    depends_on:
      db:
        condition: service_healthy
    command: python main.py
    restart: always


volumes:
  db_data:

networks:
  default:
    driver: bridge
    name: config_service_network